title: Norstone | Natural Stone Veneer | Natural Stone Products
description: New dimensions in natural stone.
url: http://www.norstoneusa.com
author: Rassan Grant
markdown: kramdown
exclude:
- bower_components
gems:
- html-proofer
- jekyll-sitemap
- jekyll-feed
- jekyll-tidy
jekyll_tidy:
  compress_html: false
collections:
  collections:
    output: true
  colors:
    output: true
defaults:
  - scope:
      path: ""
      type: collections
    values:
      layout: collection
  - scope:
      path: ""
      type: colors
    values:
      layout: collection
  - scope:
      path: ""
      type: posts
    values:
      layout: blog
      permalink: /blog/:title.html
      classes: blog
sass:
  load_paths:
    - _sass
    - bower_components/foundation-sites/scss
    - bower_components/motion-ui/src
    - bower_components/owl.carousel/src/scss
uncss:
  stylesheets:            # a list of stylesheets to be processed; mandatory
    - css/norstone.css
  ignore:                 # always keep rules for these selectors; default: none
    - ".menu"
    - "/.*orbit.*/"
    - "/.*mui-.*/"
    - ".foundation-mq"
    - "/.*accordion-.*/"
    - "/.*is-closed/"
    - "/.*is-open/"
    - !!js/regexp ^\.is-.*
  files:                  # html files to consider, globs are supported; default: **/*.html
    - "**/*.html"
    - "**/*.htm"
