# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
defaults: &defaults
  working_directory: ~/repo
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run:
          name: Install "rsync"
          command: |
            sudo apt-get update
            sudo apt-get install rsync --fix-missing
      - restore_cache:
          name: Getting Cached Ruby Dependencies
          keys:
            - v1-ruby-deps-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby Dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
          environment:
            NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      - save_cache:
          name: Caching Ruby Dependencies
          paths:
            - ./vendor/bundle
          key: v1-ruby-deps-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          name: Getting Cached Node Dependencies
          keys:
            - v1-node-deps-{{ checksum "package.json" }}
      - run:
          name: Install Node Dependencies
          command: npm i
      - save_cache:
          name: Caching Node Dependencies
          paths:
            - ./node_modules
          key: v1-node-deps-{{ checksum "package.json" }}
      - restore_cache:
          name: Getting Cached Bower Dependencies
          keys:
            - v1-bower-deps-{{ checksum "bower.json" }}
      - run:
          name: Install Bower Dependencies
          command: ./node_modules/.bin/bower install
      - save_cache:
          name: Caching Bower Dependencies
          paths:
            - ./bower_components
          key: v1-bower-deps-{{ checksum "bower.json" }}
      - run:
          name: Build Project in Production Mode
          command: npm run build:prod
      - run:
          name: Run Tests
          command: npm run test
      - add_ssh_keys:
          fingerprints:
            - "59:30:20:f9:49:9f:8b:86:f0:47:4d:a0:e2:bb:89:9b"
      - run:
          name: Add Webenabled Server as Known Host
          command: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run: 
          name: Deploying to Webenabled
          command: rsync -avce ssh _site/ w_nrstn@nrstn.prod3.webenabled.net:~/public_html/norstoneusa.com/pub
