---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections:
- path: _posts
  label: Posts
  create: all
- path: _products
  label: Products
  create: all
- path: _colors
  label: Colors
  create: all
- path: _gallery_lists
  label: Gallery_lists
  create: all
- path: _galleries
  label: Galleries
  create: all
- path: ''
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
