name: Build
on:
  push:
    branches: develop
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    name: Jekyll build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - name: Run gulp
        run: |
          npm install
          gulp build
      - name: Upload to Webenabled
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete -vvv
          rsh: "-o HostKeyAlgorithms=ssh-rsa,ssh-dss -o KexAlgorithms=diffie-hellman-group1-sha1 -o Ciphers=aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc -o HostKeyAlgorithms=ssh-dss -o PubkeyAcceptedKeyTypes=ssh-rsa"
          path: _site/
          remote_path: /home/clients/websites/w_nrstn/public_html/norstoneusa.com/pub
          remote_host: nrstn.prod3.webenabled.net
          remote_user: w_nrstn
          remote_key: ${{ secrets.DEPLOY_KEY }}
